#let HEARTBEAT_TIMER = [TIM5]
#let HEARTBEAT_INTERVAL = $5 m s$
#let HEARTBEAT_INTERVAL_MS = 5
#let HEARTBEAT_FREQUENCY = $200 H z$
#let HEARTBEAT_FREQUENCY_KHZ = 0.2
#let ACTUATOR_TIMER = [TIM9]
#let ACTUATOR_INTERVAL = $25 mu s$
#let ACTUATOR_FREQUENCY = $40 k H z$
#let ACTUATOR_FREQUENCY_KHZ = 40

#let XY_SATURATION = 4000
#let Z_MIN = 10
#let Z_MAX = 4000

#let MISS_THRESHOLD = 20
#let PID_OUTPUT_LIMIT = 0.25
